//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.IQCWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IQCWebService.IQCWebServiceSoap")]
    public interface IQCWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCheckInfoList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Test.IQCWebService.CheckInfo[] GetCheckInfoList(string checkNo);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string checkNoField;
        
        private string stockNoField;
        
        private string sapField;
        
        private string sapDetailField;
        
        private string serverCodeField;
        
        private string serverNameField;
        
        private int checkNumField;
        
        private int goodsNumField;
        
        private int notGoodNumField;
        
        private string memoField;
        
        private string errorInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CheckNo {
            get {
                return this.checkNoField;
            }
            set {
                this.checkNoField = value;
                this.RaisePropertyChanged("CheckNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StockNo {
            get {
                return this.stockNoField;
            }
            set {
                this.stockNoField = value;
                this.RaisePropertyChanged("StockNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Sap {
            get {
                return this.sapField;
            }
            set {
                this.sapField = value;
                this.RaisePropertyChanged("Sap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SapDetail {
            get {
                return this.sapDetailField;
            }
            set {
                this.sapDetailField = value;
                this.RaisePropertyChanged("SapDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ServerCode {
            get {
                return this.serverCodeField;
            }
            set {
                this.serverCodeField = value;
                this.RaisePropertyChanged("ServerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ServerName {
            get {
                return this.serverNameField;
            }
            set {
                this.serverNameField = value;
                this.RaisePropertyChanged("ServerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int CheckNum {
            get {
                return this.checkNumField;
            }
            set {
                this.checkNumField = value;
                this.RaisePropertyChanged("CheckNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int GoodsNum {
            get {
                return this.goodsNumField;
            }
            set {
                this.goodsNumField = value;
                this.RaisePropertyChanged("GoodsNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int NotGoodNum {
            get {
                return this.notGoodNumField;
            }
            set {
                this.notGoodNumField = value;
                this.RaisePropertyChanged("NotGoodNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ErrorInfo {
            get {
                return this.errorInfoField;
            }
            set {
                this.errorInfoField = value;
                this.RaisePropertyChanged("ErrorInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQCWebServiceSoapChannel : Test.IQCWebService.IQCWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QCWebServiceSoapClient : System.ServiceModel.ClientBase<Test.IQCWebService.IQCWebServiceSoap>, Test.IQCWebService.IQCWebServiceSoap {
        
        public QCWebServiceSoapClient() {
        }
        
        public QCWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QCWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QCWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QCWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Test.IQCWebService.CheckInfo[] GetCheckInfoList(string checkNo) {
            return base.Channel.GetCheckInfoList(checkNo);
        }
    }
}
